import NrmaCarbonOffset from "@/public/NrmaCarbonOffset.png"
import AppworxReachApp from "@/public/AppworxReachApp.png"
import AwsArchitectureDiagram from "@/public/AwsArchitectureDiagram.png"

export const projectsData = [
    {
        projectId: 0,
        title: "My Portfolio website", 
        place: "Auckland, NZ",
        projectType: "Frontend",
        date: "August 2021",
        description: "Learnt about new tech such as React and TailwindCSS to build this Portfolio website to help me find new opportunities and promote myself.",
        tags: ["ReactJS", "TailwindCSS", "Netlify", "React-Router", "Github",],
        link: "https://github.com/Patrik-Star/my-Portfolio",
        imageUrl: "",
    },
    {
        projectId: 1,
        title: "REACH!", 
        place: "Appworxs LTD",
        projectType: "Mobile",
        date: "2021",
        "image": "",
        description: "During my internship at Appworx, I developed the iOS version of \"Reach!\" along side the Andriod developer and published it successfully to the Apple iOS app store. ",
        tags: ["Swift", "UI Kit", "Apple", "App store", "iOS", "Mobile", "Apple Compliance", "UI design"],
        link: "https://appworx.nz/shop/",
        imageUrl: AppworxReachApp,
    },
    {
        projectId: 2,
        title: "Orbit Travel Wellington", 
        place: "Datacom NZ",
        projectType: "AWS",
        date: "Feburary 2022",
        description: "Writing Infrastructre as code using AWS's CDK to write code in Typescript to deploy infrastructre such as VPC, Subnets, NACL, Security Groups, Databases, EC2 and Lambda function.",
        tags: ["AWS", "AWS CDK", "Typescript", "AWS Architecture", "AWS Lambda"],
        link: "https://www.orbit.co.nz",
        imageUrl: "",
    },
    {
        projectId: 3,
        title: "Wise Online", 
        place: "Wise Employment Australia",
        projectType: "Full-Stack",
        date: "August 2022",
        description: "Doing full-stack development using Java springboot microservice architecture to implement a new feature to their existing application.",
        tags: ["Java", "Java Sprintboot", "VueJS", "Openshift", "PostgresSQL", "PG Admin"],
        link: "https://wiseemployment.com.au",
        imageUrl: "",
    },
    {
        projectId: 4,
        title: "Support Crew", 
        place: "Datacom NZ",
        projectType: "Full-Stack",
        date: "August 2022",
        description: "During my time in the Graduate program, I made UI designs in figma following mobile first approach and UI/UX best practices.",
        tags: ["Figma", "UI design", "UX process", "Mentorship", "Mobile"],
        link: "https://www.supportcrew.co",
        imageUrl: "",
    },
    {
        projectId: 5,
        title: "DJMIA", 
        place: "Datacom NZ",
        projectType: "Cloud Development",
        date: "September 2022",
        description: "Writing Infrastructre as code in Typescript to use AWS's CDK to deploy resources in AWS such as lambda functions in nodeJS while using Selenium, Deployed using Docker containers.",
        tags: ["AWS", "AWS CDK", "Typescript", "AWS Architecture", "AWS Lambda", "AWS SQS", "AWS SNS", "NodeJs", "DynamoDB", "Selenium", "Docker"],
        link: "Internal Project",
        imageUrl: AwsArchitectureDiagram,
    },
    {
        projectId: 6,
        title: "Carbon Offset", 
        place: "IAG",
        projectType: "Full-Stack",
        date: "November 2023",
        description: "Updating and maintaining both frontend and backend code for a web application, producing high quality UI and updating our REST API backend to add aditional features. ",
        tags: ["ReactJS", "TailwindCSS", "Typescript", "Cypress testing", "Jest", "Figma", "Jira", "Nodejs", "expressjs", "REST API", "DynamoDB", "Git", "GitHub","Teamwork", "Agile", "Bitbucket", "CI/CD", "Apigee", "Akamai", "Stripe integration"],
        link: "https://carbonoffsets.nrma.com.au/climate/",
        imageUrl: NrmaCarbonOffset,
    },
    {
        projectId: 7,
        title: "Portfolio website 2.0",
        place: "Auckland, NZ",
        projectType: "Frontend",
        date: "Jan 2024",
        description: "After feedback and self reflection of my first portfolio website, I felt the need to redo my portfolio website. I was able to improve my UI design and to further help me find new opportunities and promote myself.",
        tags: ["NextJs", "Tailwind CSS", "Typescript", "App Router", "Server Actions", "React Email", "Resend", "Framer Motion", "Vercel Hosting", "Github"], 
        link: "",
        imageUrl: "",
    },
    {
        projectId: 8,
        title: "Mulesoft Experience Hub", 
        place: "IAG",
        projectType: "Frontend",
        date: "Feb 2024",
        description: "This project was using a no-code platform called Anypoint Experience hub, which was developed by Mulesoft. I was able to deliver an API developer portal using Anypoint Exchange and Experience hub, incorporating Salesforce Identity management.",
        tags: ["Mulesoft", "Anypoint", "Anypoint Exchange", "Anypoint Experience Hub", "Salesforce", "HTML", "CSS"],
        link: "Internal Project",
        imageUrl: "",
    },
    {
        projectId: 9,
        title: "Datacom Internal POC's", 
        place: "Datacom",
        projectType: "Frontend",
        date: "June 2024",
        description: "Developing 2 brand new web applications from the ground up to test and validate business proposals. By Using the latest Technology in Full stack development, I was able to build a lightweight, robust, high-performance, customisable and easily scalable full-stack application that incorporates Authentication and database management. ",
        tags: ["NextJs", "TailwindCSS", "Typescript", "Shadcn UI", "Axios", "Vercel", "Teamwork", "Agile"],
        link: "Internal Project",
        imageUrl: "",
    },
    {
        projectId: 10,
        title: "Customer Portal ", 
        place: "Pacific Edge",
        projectType: "Full-Stack",
        date: "September 2024",
        description: "Developing in React, and by writing GraphQL queries, I was able to deliver high performance React components that incorporated server-side validation and pagination So that we can follow industry best practices for frontend developing to insure we deliviered the best solution possible to our customer.",
        tags: ["ReactJS", "Mantine UI", "Typescript", ".NET", "C#", "Figma", "Jira", "GraphQL", "MS SQL", "GitLab","Teamwork", "Agile"],
        link: "https://www.pacificedgedx.com/",
        imageUrl: "",
    },
    {
        projectId: 11,
        title: "Discord Clone", 
        place: "Auckland NZ",
        projectType: "Full-Stack",
        date: "October 2024",
        description: "Using my favourite tech stack for full-stack development, building and deploying a clone of the popular Discord video conferencing app. ",
        tags: ["NextJs", "ReactJS", "Typescript", "REST API", "Clerk Authentication", "Prisma ORM", "LiveKit", "MySQL", "Aiven DB Hosting", "uploadThing Blob Storage", "Github"],
        link: "Internal Project",
        imageUrl: "",
    },
    {
        projectId: 12,
        title: "Customer Admin Portal", 
        place: "Pushpay",
        projectType: "Frontend",
        date: "November 2024",
        description: "Building Industry level Customer Admin Portal at a high and robust standard to meet customer requirements while using modern tools and best Frontend practices.",
        tags: ["React JS", "JSS", "Typescript", "Storybook", "New Relic", "Jenkins", "Jira", "Storybooks", "Slack", "Github"],
        link: "https://pushpay.com/product/church-giving/",
        imageUrl: "",
    },
    {
        projectId: 13,
        title: "Embedded Giving", 
        place: "Pushpay",
        projectType: "Frontend",
        date: "February 2025",
        description: "Migrating a Legacy React project to a modern, high and robust standard to meet customer requirements. ",
        tags: ["React JS", "CSS", "Typescript", "Storybook", "Jenkins", "Jira", "Storybooks", "Slack", "Github"],
        link: "https://pushpay.com/product/church-giving/",
        imageUrl: "",
    },
] as const
